name = "BuchbergerLearning"
uuid = "d825c049-4a4c-479e-af9c-14b6e5d3b281"
authors = ["Nicolaus Jacobsen <jacobsen@rptu.de>"]
version = "0.1.0-DEV"

[deps]
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Oscar = "1.5.0"
Random = "1.11.0"
Test = "1.11.0"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
